name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build-images:
    strategy:
      matrix:
        version: ['3.7', '3.8', '3.9', '3.10']
    name: Build Python Docker images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build pypbars ${{ matrix.version }} image
        run:
          docker image build --build-arg PYTHON_VERSION=${{ matrix.version }} -t pypbars:${{ matrix.version }} .
      - name: save pypbars ${{ matrix.version }} image
        if: ${{ matrix.version == '3.9' }}
        run: |
          mkdir -p images
          docker save --output images/pypbars-${{ matrix.version }}.tar pypbars:${{ matrix.version }}
      - name: upload pypbars ${{ matrix.version }} image artifact
        if: ${{ matrix.version == '3.9' }}
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: images/pypbars-${{ matrix.version }}.tar
  coverage:
    name: Publish Code Coverage Report
    needs: build-images
    runs-on: ubuntu-20.04
    steps:
      - name: download image artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: images/
      - name: load image
        run:
          docker load --input images/pypbars-3.9.tar
      - name: prepare report
        run: |
          ID=$(docker create pypbars:3.9)
          docker cp $ID:/code/target/reports/pypbars_coverage.xml pypbars_coverage.xml
          sed -i -e 's,filename="pypbars/,filename="src/main/python/pypbars/,g' pypbars_coverage.xml
      - name: upload report
        uses: codecov/codecov-action@v3
        with:
          file: pypbars_coverage.xml